#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.7.0
// Descriptor size: 27 (bytes)
// +----------+--------+-------------------+
// | ReportId | Kind   | ReportSizeInBytes |
// +----------+--------+-------------------+
// |        1 | Input  |                64 |
// +----------+--------+-------------------+
// |        1 | Output |                64 |
// +----------+--------+-------------------+
static const uint8_t hidReportDescriptor[] = 
{
    0x06, 0xD0, 0xF1,    // UsagePage(FIDO Alliance[0xF1D0])
    0x09, 0x01,          // UsageId(U2F Authenticator Device[0x0001])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x01,          //     ReportId(1)
    0x09, 0x20,          //     UsageId(Input Report Data[0x0020])
    0x15, 0x00,          //     LogicalMinimum(0)
    0x26, 0xFF, 0x00,    //     LogicalMaximum(255)
    0x95, 0x40,          //     ReportCount(64)
    0x75, 0x08,          //     ReportSize(8)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x21,          //     UsageId(Output Report Data[0x0021])
    0x91, 0x02,          //     Output(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0xC0,                // EndCollection()
};

#pragma pack(push,1)

#define HID_REPORT_INPUT1_ID (1)
struct HidReportInput1
{
    uint8_t ReportId = HID_REPORT_INPUT1_ID;
    uint8_t Payload[64];
};

#define HID_REPORT_OUTPUT1_ID (1)
struct HidReportOutput1
{
    uint8_t ReportId = HID_REPORT_OUTPUT1_ID;
    uint8_t Payload[64];
};

#pragma pack(pop)