package com.chimali

import android.app.Application
import com.chimali.core.bluetooth.di.bluetoothModule
import com.chimali.core.clipboard.di.clipboardModule
import com.chimali.core.common.di.DispatchersModule
import com.chimali.core.database.di.databaseModule
import com.chimali.core.security.di.SecurityModule
import com.chimali.fido2.Fido2Initializer
import com.chimali.fido2.di.Fido2Module
import com.chimali.feature.vault.internal.vaultModule
import org.koin.android.ext.koin.androidContext
import org.koin.android.ext.koin.androidLogger
import org.koin.core.context.startKoin
import org.koin.ksp.generated.module

class ChimaliApplication : Application() {
    override fun onCreate() {
        super.onCreate()

        // Initialize Koin dependency injection using Koin Annotations compile-time modules (T189).
        // Each XxxModule().module references the KSP-generated wiring for that annotation module.
        startKoin {
            androidLogger()
            androidContext(this@ChimaliApplication)
            modules(
                // Core modules (annotation-based — generated by KSP)
                DispatchersModule().module,
                SecurityModule().module,
                // Core modules (DSL — migrated in subsequent phases)
                clipboardModule,
                databaseModule,
                bluetoothModule,
                // Feature modules (annotation-based — generated by KSP)
                Fido2Module().module,
                // Feature modules (DSL — migrated in subsequent phases)
                vaultModule,
            )
        }

        // Initialize Timber logging and local crash reporting parameters.
        // We use BuildConfig's debug status from the app module.
        Fido2Initializer.init(this, BuildConfig.DEBUG)
    }
}
