package com.chimali

import android.app.Application
import com.chimali.core.bluetooth.di.bluetoothModule
import com.chimali.core.clipboard.di.ClipboardModule
import com.chimali.core.common.di.DispatchersModule
import com.chimali.core.common.di.dataStoreModule
import com.chimali.core.data.di.coreDataModule
import com.chimali.core.database.di.databaseModule
import com.chimali.core.domain.di.DomainModule
import com.chimali.core.security.di.SecurityModule
import com.chimali.feature.onboarding.di.onboardingModule
import com.chimali.feature.settings.di.settingsModule
import com.chimali.feature.vault.internal.vaultModule
import com.chimali.fido2.Fido2Initializer
import com.chimali.fido2.di.Fido2Module
import java.security.Security
import org.bouncycastle.jce.provider.BouncyCastleProvider
import org.koin.android.ext.koin.androidContext
import org.koin.android.ext.koin.androidLogger
import org.koin.core.context.startKoin
import org.koin.ksp.generated.module

class ChimaliApplication : Application() {
    override fun onCreate() {
        super.onCreate()

        // Register BouncyCastle globally once at application startup for non-SIV
        // cryptographic capabilities (HDK, PQC, etc.).
        Security.addProvider(BouncyCastleProvider())

        // Initialize Koin dependency injection using Koin Annotations compile-time modules (T189).
        // Each XxxModule().module references the KSP-generated wiring for that annotation module.
        startKoin {
            androidLogger()
            androidContext(this@ChimaliApplication)
            modules(
                // Core modules (annotation-based — generated by KSP)
                DomainModule().module,
                DispatchersModule().module,
                SecurityModule().module,
                // Core modules (DSL — migrated in subsequent phases)
                dataStoreModule,
                ClipboardModule().module,
                databaseModule,
                coreDataModule,
                bluetoothModule,
                // Feature modules (annotation-based — generated by KSP)
                Fido2Module().module,
                // Feature modules (DSL — migrated in subsequent phases)
                onboardingModule,
                settingsModule,
                vaultModule,
            )
        }

        // Initialize Timber logging and local crash reporting parameters.
        // We use BuildConfig's debug status from the app module.
        Fido2Initializer.init(this)
    }
}
