syntax = "proto3";

import "app/chimali/data/dark_theme_config.proto";
import "app/chimali/data/theme_brand.proto";

option java_package = "app.chimali.core.datastore";
option java_multiple_files = true;

message UserPreferences {
    reserved 2;
    int32 migration_version = 1;

    bool should_hide_onboarding = 3;
    string last_visited_main_screen = 4;

    ThemeBrandProto theme_brand = 11;
    DarkThemeConfigProto dark_theme_config = 12;
    bool use_dynamic_color = 13;

    // Each map is used to store a set of string IDs. The bool has no meaning, but proto3 doesn't
    // have a Set type so this is the closest we can get to a Set.
    map<string, bool> selected_app_feature_ids = 21;

    // NEXT AVAILABLE ID: 22
}
